// movie actions
export const MOVIES_GET_MOVIES = 'MOVIES_GET_MOVIES';
export const MOVIES_SET_MOVIES = 'MOVIES_SET_MOVIES';
export const MOVIES_GET_DETAILS = 'MOVEIS_GET_DETAILS';
export const MOVIES_SET_DETAILS = 'MOVEIS_SET_DETAILS';
export const MOVIES_CLEAR_DETAILS = 'MOVIES_CLEAR_DETAILS';
export const MOVIES_SET_PEOPLE = 'MOVIES_SET_PEOPLE';
