// movie actions
export const MOVIES_GET_MOVIES = 'MOVIES_GET_MOVIES';
export const MOVIES_SET_MOVIES = 'MOVIES_SET_MOVIES';
export const MOVIES_GET_DETAILS = 'MOVEIS_GET_DETAILS';
export const MOVIES_SET_DETAILS = 'MOVEIS_SET_DETAILS';
export const MOVIES_CLEAR_DETAILS = 'MOVIES_CLEAR_DETAILS';
export const MOVIES_SET_PEOPLE = 'MOVIES_SET_PEOPLE';
export const MOVIES_SET_PHOTOS = 'MOVIES_SET_PHOTOS';
export const MOVIES_RELOAD_DETAILS = 'MOVIES_RELOAD_DETAILS';

// page actions
export const PAGE_RELOAD = 'PAGE_RELOAD';

// admin actions
export const ADMIN_EDIT = 'ADMIN_EDIT';
export const ADMIN_CLEAR_DETAILS = 'ADMIN_CLEAR_DETAILS';
export const ADMIN_RELOAD_DETAILS = 'ADMIN_RELOAD_DETAILS';
export const ADMIN_SET_PHOTOS = 'ADMIN_SET_PHOTOS';
export const ADMIN_SET_PEOPLE = 'ADMIN_SET_PEOPLE';
export const ADMIN_SET_DETAILS = 'ADMIN_SET_DETAILS';

// site actions
export const SITE_UPDATE_RECENTS = 'SITE_UPDATE_RECENTS';
